import type { Metadata } from "next";
import { Readex_Pro } from "next/font/google";
import "./globals.css";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";

const readexPro = Readex_Pro({
  subsets: ["latin"],
  variable: "--font-readex-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${readexPro.variable} antialiased h-svh`}>
        {/* <BackgroundBeamsWithCollision>{children}</BackgroundBeamsWithCollision> */}
        Empty
      </body>
    </html>
  );
}
